### ISSUE TITLE
Как правильно добавить ещё один тегсет?

### ISSUE THREAD

**Issue by victorbocharov** [kmike/russian-tagsets#3]
В связи с соревнованием RuMorphoEval (на Диалоге в 2017), похоже, что нужен конвертер из OpenCorpora в UD (http://universaldependencies.org/ru/pos/all.html). С чего лучше начать, чтобы его сделать и встроить сюда?

**Comment by kmike** [comment]
Привет! 

Для этого нужно создать новый модуль и добавить функцию, которая принимает тег из одного тегсета и возвращает тег из другого, а потом зарегистрировать ее. Например, как тут: https://github.com/kmike/russian-tagsets/blob/969eafe22a92bb612bb1f2e111404edfac133971/russian_tagsets/opencorpora.py#L163 (и потом `converters.add('opencorpora-ext', 'aot', to_aot)`). 

Для того, чтоб было проще писать (и читать) такие функции, есть DSL для написания правил. Так, например, реализовано преобразование OpenCorpora -> НКРЯ: https://github.com/kmike/russian-tagsets/blob/969eafe22a92bb612bb1f2e111404edfac133971/russian_tagsets/ruscorpora.py#L30

Еще хорошо, если есть тесты; для OpenCorpora -> НКРЯ делал так: брал по  ~10 примеров на каждую граммему, с разными тегами, и прописывал, какой тег нужно получить; потом смотрел, что из этого не работает, и уточнял правила. Это неидеально (есть случаи, которые сложно получить случайным образом - их можно добавлять вручную, если они находятся), до все-таки дает более-менее хорошее покрытие. См. https://github.com/kmike/russian-tagsets/blob/master/russian_tagsets/tests/test_ruscorpora.py

Что в этой библиотеке неправильно: теги преобразуются без учета слова. Это не позволяет обработать случаи, когда разные наборы тегов используют разные подходы для разметки каких-то отдельных слов - ну, например, кто-то считает слово предикативом, а кто-то нет.

**Comment by grandsbor** [comment]
Думаю, можно закрыть (см. #4)
